package ru.zagorodnikova.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-19T18:44:10.854+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", name = "ProjectEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/sortProjectsByDateStartRequest", output = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/sortProjectsByDateStartResponse")
    @RequestWrapper(localName = "sortProjectsByDateStart", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortProjectsByDateStart")
    @ResponseWrapper(localName = "sortProjectsByDateStartResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortProjectsByDateStartResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.endpoint.Project> sortProjectsByDateStart(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/sortProjectsByDateFinishRequest", output = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/sortProjectsByDateFinishResponse")
    @RequestWrapper(localName = "sortProjectsByDateFinish", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortProjectsByDateFinish")
    @ResponseWrapper(localName = "sortProjectsByDateFinishResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortProjectsByDateFinishResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.endpoint.Project> sortProjectsByDateFinish(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/mergeProjectRequest", output = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/mergeProjectResponse")
    @RequestWrapper(localName = "mergeProject", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.MergeProject")
    @ResponseWrapper(localName = "mergeProjectResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.MergeProjectResponse")
    public void mergeProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/sortProjectsByDateCreatedRequest", output = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/sortProjectsByDateCreatedResponse")
    @RequestWrapper(localName = "sortProjectsByDateCreated", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortProjectsByDateCreated")
    @ResponseWrapper(localName = "sortProjectsByDateCreatedResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortProjectsByDateCreatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.endpoint.Project> sortProjectsByDateCreated(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/removeProjectRequest", output = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/removeProjectResponse")
    @RequestWrapper(localName = "removeProject", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveProject")
    @ResponseWrapper(localName = "removeProjectResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveProjectResponse")
    public void removeProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/sortProjectsByStatusRequest", output = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/sortProjectsByStatusResponse")
    @RequestWrapper(localName = "sortProjectsByStatus", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortProjectsByStatus")
    @ResponseWrapper(localName = "sortProjectsByStatusResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortProjectsByStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.endpoint.Project> sortProjectsByStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/findAllProjectsRequest", output = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/findAllProjectsResponse")
    @RequestWrapper(localName = "findAllProjects", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.FindAllProjects")
    @ResponseWrapper(localName = "findAllProjectsResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.FindAllProjectsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.endpoint.Project> findAllProjects(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/removeAllProjectsRequest", output = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/removeAllProjectsResponse")
    @RequestWrapper(localName = "removeAllProjects", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveAllProjects")
    @ResponseWrapper(localName = "removeAllProjectsResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveAllProjectsResponse")
    public void removeAllProjects(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/persistProjectRequest", output = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/persistProjectResponse")
    @RequestWrapper(localName = "persistProject", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.PersistProject")
    @ResponseWrapper(localName = "persistProjectResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.PersistProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.zagorodnikova.tm.endpoint.Project persistProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/findOneProjectRequest", output = "http://endpoint.tm.zagorodnikova.ru/ProjectEndpoint/findOneProjectResponse")
    @RequestWrapper(localName = "findOneProject", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.FindOneProject")
    @ResponseWrapper(localName = "findOneProjectResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.FindOneProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.zagorodnikova.tm.endpoint.Project findOneProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
