package ru.zagorodnikova.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-19T18:44:11.268+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", name = "SessionEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface SessionEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/SessionEndpoint/persistRequest", output = "http://endpoint.tm.zagorodnikova.ru/SessionEndpoint/persistResponse")
    @RequestWrapper(localName = "persist", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.Persist")
    @ResponseWrapper(localName = "persistResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.PersistResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.zagorodnikova.tm.endpoint.Session persist(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.zagorodnikova.tm.endpoint.User arg0
    );
}
