package ru.zagorodnikova.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-19T18:44:11.167+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", name = "TaskEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface TaskEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/sortTasksByDateStartRequest", output = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/sortTasksByDateStartResponse")
    @RequestWrapper(localName = "sortTasksByDateStart", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortTasksByDateStart")
    @ResponseWrapper(localName = "sortTasksByDateStartResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortTasksByDateStartResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.endpoint.Task> sortTasksByDateStart(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/sortTasksByDateFinishRequest", output = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/sortTasksByDateFinishResponse")
    @RequestWrapper(localName = "sortTasksByDateFinish", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortTasksByDateFinish")
    @ResponseWrapper(localName = "sortTasksByDateFinishResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortTasksByDateFinishResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.endpoint.Task> sortTasksByDateFinish(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/sortTasksByStatusRequest", output = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/sortTasksByStatusResponse")
    @RequestWrapper(localName = "sortTasksByStatus", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortTasksByStatus")
    @ResponseWrapper(localName = "sortTasksByStatusResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortTasksByStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.endpoint.Task> sortTasksByStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/removeTaskRequest", output = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/removeTaskResponse")
    @RequestWrapper(localName = "removeTask", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveTask")
    @ResponseWrapper(localName = "removeTaskResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveTaskResponse")
    public void removeTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/removeAllTasksRequest", output = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/removeAllTasksResponse")
    @RequestWrapper(localName = "removeAllTasks", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveAllTasks")
    @ResponseWrapper(localName = "removeAllTasksResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveAllTasksResponse")
    public void removeAllTasks(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/findAllTasksInProjectRequest", output = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/findAllTasksInProjectResponse")
    @RequestWrapper(localName = "findAllTasksInProject", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.FindAllTasksInProject")
    @ResponseWrapper(localName = "findAllTasksInProjectResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.FindAllTasksInProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.endpoint.Task> findAllTasksInProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/removeAllTasksInProjectRequest", output = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/removeAllTasksInProjectResponse")
    @RequestWrapper(localName = "removeAllTasksInProject", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveAllTasksInProject")
    @ResponseWrapper(localName = "removeAllTasksInProjectResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveAllTasksInProjectResponse")
    public void removeAllTasksInProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/persistTaskRequest", output = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/persistTaskResponse")
    @RequestWrapper(localName = "persistTask", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.PersistTask")
    @ResponseWrapper(localName = "persistTaskResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.PersistTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.zagorodnikova.tm.endpoint.Task persistTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/mergeTaskRequest", output = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/mergeTaskResponse")
    @RequestWrapper(localName = "mergeTask", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.MergeTask")
    @ResponseWrapper(localName = "mergeTaskResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.MergeTaskResponse")
    public void mergeTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/findOneTaskRequest", output = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/findOneTaskResponse")
    @RequestWrapper(localName = "findOneTask", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.FindOneTask")
    @ResponseWrapper(localName = "findOneTaskResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.FindOneTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.zagorodnikova.tm.endpoint.Task findOneTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/sortTasksByDateCreatedRequest", output = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/sortTasksByDateCreatedResponse")
    @RequestWrapper(localName = "sortTasksByDateCreated", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortTasksByDateCreated")
    @ResponseWrapper(localName = "sortTasksByDateCreatedResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SortTasksByDateCreatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.endpoint.Task> sortTasksByDateCreated(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/findAllTasksRequest", output = "http://endpoint.tm.zagorodnikova.ru/TaskEndpoint/findAllTasksResponse")
    @RequestWrapper(localName = "findAllTasks", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.FindAllTasks")
    @ResponseWrapper(localName = "findAllTasksResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.FindAllTasksResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.endpoint.Task> findAllTasks(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
