package ru.zagorodnikova.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-19T18:44:11.017+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", name = "UserEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/changePasswordRequest", output = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/changePasswordResponse")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.ChangePasswordResponse")
    public void changePassword(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/signUpRequest", output = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/signUpResponse")
    @RequestWrapper(localName = "signUp", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SignUp")
    @ResponseWrapper(localName = "signUpResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SignUpResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.zagorodnikova.tm.endpoint.User signUp(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/findAllUsersRequest", output = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/findAllUsersResponse")
    @RequestWrapper(localName = "findAllUsers", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.FindAllUsers")
    @ResponseWrapper(localName = "findAllUsersResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.FindAllUsersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.endpoint.User> findAllUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.zagorodnikova.tm.endpoint.RoleType arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/updateUserRequest", output = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/updateUserResponse")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.UpdateUserResponse")
    public void updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/signInRequest", output = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/signInResponse")
    @RequestWrapper(localName = "signIn", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SignIn")
    @ResponseWrapper(localName = "signInResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.SignInResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.zagorodnikova.tm.endpoint.User signIn(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/removeUserRequest", output = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/removeUserResponse")
    @RequestWrapper(localName = "removeUser", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveUser")
    @ResponseWrapper(localName = "removeUserResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveUserResponse")
    public void removeUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/removeAllUsersRequest", output = "http://endpoint.tm.zagorodnikova.ru/UserEndpoint/removeAllUsersResponse")
    @RequestWrapper(localName = "removeAllUsers", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveAllUsers")
    @ResponseWrapper(localName = "removeAllUsersResponse", targetNamespace = "http://endpoint.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.endpoint.RemoveAllUsersResponse")
    public void removeAllUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
