package ru.zagorodnikova.tm.api.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-18T19:04:13.356+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://service.api.tm.zagorodnikova.ru/", name = "IProjectService")
@XmlSeeAlso({ObjectFactory.class})
public interface IProjectService {

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/IProjectService/mergeProjectRequest", output = "http://service.api.tm.zagorodnikova.ru/IProjectService/mergeProjectResponse")
    @RequestWrapper(localName = "mergeProject", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.MergeProject")
    @ResponseWrapper(localName = "mergeProjectResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.MergeProjectResponse")
    public void mergeProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/IProjectService/sortProjectsByDateCreatedRequest", output = "http://service.api.tm.zagorodnikova.ru/IProjectService/sortProjectsByDateCreatedResponse")
    @RequestWrapper(localName = "sortProjectsByDateCreated", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortProjectsByDateCreated")
    @ResponseWrapper(localName = "sortProjectsByDateCreatedResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortProjectsByDateCreatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.api.service.Project> sortProjectsByDateCreated(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/IProjectService/sortProjectsByDateFinishRequest", output = "http://service.api.tm.zagorodnikova.ru/IProjectService/sortProjectsByDateFinishResponse")
    @RequestWrapper(localName = "sortProjectsByDateFinish", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortProjectsByDateFinish")
    @ResponseWrapper(localName = "sortProjectsByDateFinishResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortProjectsByDateFinishResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.api.service.Project> sortProjectsByDateFinish(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/IProjectService/sortProjectsByDateStartRequest", output = "http://service.api.tm.zagorodnikova.ru/IProjectService/sortProjectsByDateStartResponse")
    @RequestWrapper(localName = "sortProjectsByDateStart", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortProjectsByDateStart")
    @ResponseWrapper(localName = "sortProjectsByDateStartResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortProjectsByDateStartResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.api.service.Project> sortProjectsByDateStart(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/IProjectService/removeAllProjectsRequest", output = "http://service.api.tm.zagorodnikova.ru/IProjectService/removeAllProjectsResponse")
    @RequestWrapper(localName = "removeAllProjects", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.RemoveAllProjects")
    @ResponseWrapper(localName = "removeAllProjectsResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.RemoveAllProjectsResponse")
    public void removeAllProjects(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/IProjectService/persistProjectRequest", output = "http://service.api.tm.zagorodnikova.ru/IProjectService/persistProjectResponse")
    @RequestWrapper(localName = "persistProject", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.PersistProject")
    @ResponseWrapper(localName = "persistProjectResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.PersistProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.zagorodnikova.tm.api.service.Project persistProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/IProjectService/findOneProjectRequest", output = "http://service.api.tm.zagorodnikova.ru/IProjectService/findOneProjectResponse")
    @RequestWrapper(localName = "findOneProject", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.FindOneProject")
    @ResponseWrapper(localName = "findOneProjectResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.FindOneProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.zagorodnikova.tm.api.service.Project findOneProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/IProjectService/removeProjectRequest", output = "http://service.api.tm.zagorodnikova.ru/IProjectService/removeProjectResponse")
    @RequestWrapper(localName = "removeProject", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.RemoveProject")
    @ResponseWrapper(localName = "removeProjectResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.RemoveProjectResponse")
    public void removeProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/IProjectService/sortProjectsByStatusRequest", output = "http://service.api.tm.zagorodnikova.ru/IProjectService/sortProjectsByStatusResponse")
    @RequestWrapper(localName = "sortProjectsByStatus", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortProjectsByStatus")
    @ResponseWrapper(localName = "sortProjectsByStatusResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortProjectsByStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.api.service.Project> sortProjectsByStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/IProjectService/findAllProjectsRequest", output = "http://service.api.tm.zagorodnikova.ru/IProjectService/findAllProjectsResponse")
    @RequestWrapper(localName = "findAllProjects", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.FindAllProjects")
    @ResponseWrapper(localName = "findAllProjectsResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.FindAllProjectsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.api.service.Project> findAllProjects(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
