package ru.zagorodnikova.tm.api.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-18T19:04:13.186+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://service.api.tm.zagorodnikova.ru/", name = "ITaskService")
@XmlSeeAlso({ObjectFactory.class})
public interface ITaskService {

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/ITaskService/findAllTasksRequest", output = "http://service.api.tm.zagorodnikova.ru/ITaskService/findAllTasksResponse")
    @RequestWrapper(localName = "findAllTasks", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.FindAllTasks")
    @ResponseWrapper(localName = "findAllTasksResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.FindAllTasksResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.api.service.Task> findAllTasks(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/ITaskService/sortTasksByDateCreatedRequest", output = "http://service.api.tm.zagorodnikova.ru/ITaskService/sortTasksByDateCreatedResponse")
    @RequestWrapper(localName = "sortTasksByDateCreated", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortTasksByDateCreated")
    @ResponseWrapper(localName = "sortTasksByDateCreatedResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortTasksByDateCreatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.api.service.Task> sortTasksByDateCreated(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/ITaskService/mergeTaskRequest", output = "http://service.api.tm.zagorodnikova.ru/ITaskService/mergeTaskResponse")
    @RequestWrapper(localName = "mergeTask", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.MergeTask")
    @ResponseWrapper(localName = "mergeTaskResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.MergeTaskResponse")
    public void mergeTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/ITaskService/persistTaskRequest", output = "http://service.api.tm.zagorodnikova.ru/ITaskService/persistTaskResponse")
    @RequestWrapper(localName = "persistTask", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.PersistTask")
    @ResponseWrapper(localName = "persistTaskResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.PersistTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.zagorodnikova.tm.api.service.Task persistTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/ITaskService/findOneTaskRequest", output = "http://service.api.tm.zagorodnikova.ru/ITaskService/findOneTaskResponse")
    @RequestWrapper(localName = "findOneTask", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.FindOneTask")
    @ResponseWrapper(localName = "findOneTaskResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.FindOneTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.zagorodnikova.tm.api.service.Task findOneTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/ITaskService/sortTasksByDateStartRequest", output = "http://service.api.tm.zagorodnikova.ru/ITaskService/sortTasksByDateStartResponse")
    @RequestWrapper(localName = "sortTasksByDateStart", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortTasksByDateStart")
    @ResponseWrapper(localName = "sortTasksByDateStartResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortTasksByDateStartResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.api.service.Task> sortTasksByDateStart(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/ITaskService/removeAllTasksInProjectRequest", output = "http://service.api.tm.zagorodnikova.ru/ITaskService/removeAllTasksInProjectResponse")
    @RequestWrapper(localName = "removeAllTasksInProject", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.RemoveAllTasksInProject")
    @ResponseWrapper(localName = "removeAllTasksInProjectResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.RemoveAllTasksInProjectResponse")
    public void removeAllTasksInProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/ITaskService/removeAllTasksRequest", output = "http://service.api.tm.zagorodnikova.ru/ITaskService/removeAllTasksResponse")
    @RequestWrapper(localName = "removeAllTasks", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.RemoveAllTasks")
    @ResponseWrapper(localName = "removeAllTasksResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.RemoveAllTasksResponse")
    public void removeAllTasks(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/ITaskService/removeTaskRequest", output = "http://service.api.tm.zagorodnikova.ru/ITaskService/removeTaskResponse")
    @RequestWrapper(localName = "removeTask", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.RemoveTask")
    @ResponseWrapper(localName = "removeTaskResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.RemoveTaskResponse")
    public void removeTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/ITaskService/findAllTasksInProjectRequest", output = "http://service.api.tm.zagorodnikova.ru/ITaskService/findAllTasksInProjectResponse")
    @RequestWrapper(localName = "findAllTasksInProject", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.FindAllTasksInProject")
    @ResponseWrapper(localName = "findAllTasksInProjectResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.FindAllTasksInProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.api.service.Task> findAllTasksInProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/ITaskService/sortTasksByDateFinishRequest", output = "http://service.api.tm.zagorodnikova.ru/ITaskService/sortTasksByDateFinishResponse")
    @RequestWrapper(localName = "sortTasksByDateFinish", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortTasksByDateFinish")
    @ResponseWrapper(localName = "sortTasksByDateFinishResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortTasksByDateFinishResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.api.service.Task> sortTasksByDateFinish(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://service.api.tm.zagorodnikova.ru/ITaskService/sortTasksByStatusRequest", output = "http://service.api.tm.zagorodnikova.ru/ITaskService/sortTasksByStatusResponse")
    @RequestWrapper(localName = "sortTasksByStatus", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortTasksByStatus")
    @ResponseWrapper(localName = "sortTasksByStatusResponse", targetNamespace = "http://service.api.tm.zagorodnikova.ru/", className = "ru.zagorodnikova.tm.api.service.SortTasksByStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.zagorodnikova.tm.api.service.Task> sortTasksByStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
